/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/
import { HazardDef } from './types';

export const HAZARD_DEFS: HazardDef[] = [
  {
    id: "hazard.salt-mirage",
    name: "Salt Mirage",
    biomes: ["salt-steppe", "amber-dunes"],
    risk: { tier: 2 },
    avoid_by: ["relic:Salt Lens", "rite:Bind the Road"],
    consequence: ["time:+1 delay", "clarity:-1 if pursued"],
    echo_triggers: ["mirage_endured"],
  },
  {
    id: "hazard.fen-suck",
    name: "Fen-Suck",
    biomes: ["ash-fen", "drowned-vale"],
    risk: { tier: 3 },
    avoid_by: ["travel:road", "relic:Roadkeeper’s Token"],
    consequence: ["time:+2", "lose:relic 10%"],
    echo_triggers: ["near_loss_recorded"],
  },
  {
    id: "hazard.ivy-whisper",
    name: "Ivy-Whisper",
    biomes: ["ivythorn"],
    risk: { tier: 1 },
    avoid_by: ["remember:true_name", "mask:UNNAMED"],
    consequence: ["clarity:-1", "rumor:mislead"],
    echo_triggers: ["whisper_resisted"],
  },
  {
    id: "hazard.mask-tax",
    name: "Mask Tax",
    biomes: ["basalt-ridge"],
    risk: { tier: 2 },
    avoid_by: ["faction:Maskwrights >= friendly", "barter:token"],
    consequence: ["time:+1", "recognition:-1 if unpaid"],
    echo_triggers: ["toll_paid", "toll_defied"],
  },
  {
    id: "hazard.spirit-tithe",
    name: "Spirit Tithe",
    biomes: ["drowned-vale", "ash-fen"],
    risk: { tier: 3 },
    avoid_by: ["rite:Wake the Well", "invoke:spirit"],
    consequence: ["clarity:-2 or mark:SPIRIT-TOUCHED"],
    echo_triggers: ["tithe_recorded"],
  },
  {
    id: "hazard.rockfall",
    name: "Rockfall",
    biomes: ["basalt-ridge"],
    risk: { tier: 2 },
    avoid_by: ["travel:wait", "ask_about:roadkeepers"],
    consequence: ["time:+1", "site:blocked"],
    echo_triggers: ["detour_taken"],
  },
  {
    id: "hazard.dune-sink",
    name: "Dune Sink",
    biomes: ["amber-dunes"],
    risk: { tier: 3 },
    avoid_by: ["relic:Dune Compass", "travel:road"],
    consequence: ["time:+2", "clarity:-1"],
    echo_triggers: ["sink_escaped"],
  },
  {
    id: "hazard.mire-fever",
    name: "Mire Fever",
    biomes: ["ash-fen", "drowned-vale"],
    risk: { tier: 2 },
    avoid_by: ["rite:Share Breath", "invoke:spirit"],
    consequence: ["clarity:-2", "mark:FEVERED"],
    echo_triggers: ["illness_recorded"],
  },
  {
    id: "hazard.dust-wraith",
    name: "Dust Wraith",
    biomes: ["amber-dunes", "salt-steppe"],
    risk: { tier: 3 },
    avoid_by: ["invoke:Reed Lullaby", "relic:Lantern Coin"],
    consequence: ["clarity:-2", "time:+1", "mark:DUST-TOUCHED"],
    echo_triggers: ["wraith_banished"],
  },
  {
    id: "hazard.salt-creep",
    name: "Salt Creep",
    biomes: ["salt-steppe"],
    risk: { tier: 2 },
    avoid_by: ["rite:Brine Lustration", "travel:detour"],
    consequence: ["item:corrode 10%", "time:+1"],
    echo_triggers: ["creep_arrested"],
  },
  {
    id: "hazard.thorn-spores",
    name: "Thorn Spores",
    biomes: ["ivythorn"],
    risk: { tier: 2 },
    avoid_by: ["mask:BAPTIZED", "remember:true_name"],
    consequence: ["clarity:-1", "mark:IRRITATED"],
    echo_triggers: ["spores_endured"],
  },
  {
    id: "hazard.basalt-scree",
    name: "Basalt Scree",
    biomes: ["basalt-ridge"],
    risk: { tier: 2 },
    avoid_by: ["ask_about:Roadkeepers", "travel:wait"],
    consequence: ["time:+2", "site:blocked"],
    echo_triggers: ["scree_crossed"],
  },
  {
    id: "hazard.ferry-break",
    name: "Ferry Break",
    biomes: ["drowned-vale"],
    risk: { tier: 3 },
    avoid_by: ["relic:Roadkeeper’s Token", "rite:Bind the Road"],
    consequence: ["time:+2", "claim:lose temporary control of jetty"],
    echo_triggers: ["ferry_repaired"],
  },
  {
    id: "hazard.rope-haunt",
    name: "Rope Haunt",
    biomes: ["ash-fen"],
    risk: { tier: 3 },
    avoid_by: ["rite:Gallows Recital", "invoke:spirit"],
    consequence: ["clarity:-2", "mark:HAUNTED"],
    echo_triggers: ["haunt_survived"],
  },
  {
    id: "hazard.dune-collapse",
    name: "Dune Collapse",
    biomes: ["amber-dunes"],
    risk: { tier: 3 },
    avoid_by: ["relic:Dune Compass", "travel:detour"],
    consequence: ["time:+2", "site:buried"],
    echo_triggers: ["collapse_recorded"],
  },
  {
    id: "hazard.ivy-possession",
    name: "Ivy Possession",
    biomes: ["ivythorn"],
    risk: { tier: 3 },
    avoid_by: ["rite:Ivy Binding", "mask:UNNAMED"],
    consequence: ["clarity:-2", "mark:POSSESSED"],
    echo_triggers: ["possession_resisted"],
  },
  {
    id: "hazard.cliff-tremor",
    name: "Cliff Tremor",
    biomes: ["basalt-ridge"],
    risk: { tier: 3 },
    avoid_by: ["invoke:Choir Resonance", "travel:wait"],
    consequence: ["time:+2", "mark:TREMOR-SHAKEN"],
    echo_triggers: ["tremor_endured"],
  },
  {
    id: "hazard.ferry-wraith",
    name: "Ferry Wraith",
    biomes: ["drowned-vale"],
    risk: { tier: 2 },
    avoid_by: ["relic:Mire Torch", "rite:Bind the Road"],
    consequence: ["clarity:-1", "faction:Mirebound -1"],
    echo_triggers: ["wraith_encountered"],
  },
];