/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/
import { RelicDef } from './types';

export const RELIC_DEFS: RelicDef[] = [
  {
    id: "relic.knot-of-true-breath",
    name: "Knot of True Breath",
    rarity: "uncommon",
    tags: ["oath", "name"],
    affordances: ["pledge:+1 success if name spoken"],
    effects: [{ stat: "recognition", delta: 1, scope: "faction:Lantern Court" }],
    echo_triggers: ["oath_sworn_named"],
  },
  {
    id: "relic.salt-lens",
    name: "Salt Lens",
    rarity: "rare",
    tags: ["memory", "star"],
    affordances: ["study:reveal hidden tag at ruins"],
    effects: [{ stat: "clarity", delta: -1, scope: "action:study" }],
    echo_triggers: ["memory_recovered"],
  },
  {
    id: "relic.reed-mask.blank",
    name: "Blank Reed Mask",
    rarity: "common",
    tags: ["mask", "craft"],
    affordances: ["mask:forge at Maskwright Hall"],
    effects: [{ stat: "recognition", delta: 1, scope: "neutral" }],
    echo_triggers: ["mask_forged"],
  },
  {
    id: "relic.roadkeepers-token",
    name: "Roadkeeper’s Token",
    rarity: "uncommon",
    tags: ["travel", "road"],
    affordances: ["travel:ignore hazard tier 2 on roads"],
    effects: [],
    echo_triggers: ["safe_passage_recorded"],
  },
  {
    id: "relic.oath-pin.black-iron",
    name: "Black-Iron Oath Pin",
    rarity: "uncommon",
    tags: ["oath", "pledge"],
    affordances: ["pledge:bind without witness once"],
    effects: [{ stat: "time", delta: -1, scope: "pledge" }],
    echo_triggers: ["oath_sworn"],
  },
  {
    id: "relic.memory-vial",
    name: "Memory Vial",
    rarity: "rare",
    tags: ["memory", "bottle"],
    affordances: ["remember:store one rumor as echo-ready"],
    effects: [],
    echo_triggers: ["memory_bottled"],
  },
  {
    id: "relic.dune-compass",
    name: "Dune Compass",
    rarity: "uncommon",
    tags: ["travel", "desert"],
    affordances: ["travel:reroll hazard check once per run"],
    effects: [],
    echo_triggers: ["safe_passage_recorded"],
  },
  {
    id: "relic.brine-bell",
    name: "Brine Bell",
    rarity: "rare",
    tags: ["ocean", "salt", "warning"],
    affordances: ["invoke:ring to repel spirit hazard once"],
    effects: [{ stat: "clarity", delta: -1, scope: "invoke" }],
    echo_triggers: ["spirit_warded"],
  },
  {
    id: "relic.thorn-ledger",
    name: "Thorn Ledger",
    rarity: "uncommon",
    tags: ["trade", "ivy", "rumor"],
    affordances: ["barter:gain +1 rumor when trading at markets"],
    effects: [],
    echo_triggers: ["trade_recorded"],
  },
  {
    id: "relic.oath-thread",
    name: "Oath Thread",
    rarity: "rare",
    tags: ["oath", "binding"],
    affordances: ["pledge:bind two parties even if apart"],
    effects: [{ stat: "time", delta: 1, scope: "pledge" }],
    echo_triggers: ["oath_bound"],
  },
  {
    id: "relic.lantern-coin",
    name: "Lantern Coin",
    rarity: "uncommon",
    tags: ["currency", "spirit"],
    affordances: ["barter:pay once to avert spirit toll"],
    effects: [],
    echo_triggers: ["spirit_bribed"],
  },
  {
    id: "relic.echo-shard",
    name: "Echo Shard",
    rarity: "rare",
    tags: ["memory", "shard"],
    affordances: ["remember:copy one past echo into next run"],
    effects: [],
    echo_triggers: ["echo_carried"],
  },
  {
    id: "relic.maskwright-needle",
    name: "Maskwright’s Needle",
    rarity: "mythic",
    tags: ["mask", "craft"],
    affordances: ["mask:forge a mask with two tags at once"],
    effects: [{ stat: "recognition", delta: 3, scope: "Maskwrights" }],
    echo_triggers: ["mask_double_forged"],
  },
  {
    id: "relic.roadchalk",
    name: "Roadchalk",
    rarity: "common",
    tags: ["road", "mark"],
    affordances: ["scribe:mark safe detour at gates or milestones"],
    effects: [{ stat: "time", delta: -1, scope: "next_travel" }],
    echo_triggers: ["detour_marked"],
  },
  {
    id: "relic.basalt-chisel",
    name: "Basalt Chisel",
    rarity: "uncommon",
    tags: ["craft", "mask"],
    affordances: ["mask:add one extra cosmetic tag at forges"],
    effects: [],
    echo_triggers: ["mask_engraved"],
  },
  {
    id: "relic.reed-flute.mire",
    name: "Mire Reed-Flute",
    rarity: "uncommon",
    tags: ["music", "spirit"],
    affordances: ["invoke:calm spirit hazard once per run"],
    effects: [],
    echo_triggers: ["spirit_soothed"],
  },
  {
    id: "relic.glassbone-splinter",
    name: "Glassbone Splinter",
    rarity: "rare",
    tags: ["star", "memory"],
    affordances: ["study:see prior-night sky at ruins"],
    effects: [{ stat: "clarity", delta: -1, scope: "study" }],
    echo_triggers: ["constellation_named"],
  },
  {
    id: "relic.salt-scribe-stylus",
    name: "Salt-Scribe Stylus",
    rarity: "uncommon",
    tags: ["scribe", "salt"],
    affordances: ["scribe:convert rumor into minor bias once"],
    effects: [],
    echo_triggers: ["rumor_inscribed"],
  },
  {
    id: "relic.thorn-crown",
    name: "Thorn Crown",
    rarity: "rare",
    tags: ["oath", "ivy"],
    affordances: ["pledge:+1 success vs Ivythorn factions"],
    effects: [{ stat: "clarity", delta: -1, scope: "pledge" }],
    echo_triggers: ["crown_oath"],
  },
  {
    id: "relic.dune-veil",
    name: "Dune Veil",
    rarity: "uncommon",
    tags: ["desert", "conceal"],
    affordances: ["travel:ignore one rumor spread when masked"],
    effects: [],
    echo_triggers: ["veil_hidden"],
  },
  {
    id: "relic.pebble-memory",
    name: "Pebble of Memory",
    rarity: "common",
    tags: ["memory", "small"],
    affordances: ["remember:store one small clue temporarily"],
    effects: [],
    echo_triggers: ["memory_carried"],
  },
  {
    id: "relic.oath-chain",
    name: "Oath Chain",
    rarity: "uncommon",
    tags: ["binding", "claim"],
    affordances: ["claim:secure site with +1 strength if worn"],
    effects: [],
    echo_triggers: ["claim_bound"],
  },
  {
    id: "relic.mire-torch",
    name: "Mire Torch",
    rarity: "rare",
    tags: ["fire", "fen"],
    affordances: ["invoke:burn to banish FEVERED mark"],
    effects: [{ stat: "time", delta: 1, scope: "invoke" }],
    echo_triggers: ["torch_burned"],
  },
];