/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/
import { RiteDef } from './types';

export const RITE_DEFS: RiteDef[] = [
  {
    id: "rite.relinquish-name",
    name: "Relinquish Name",
    domain: "shadow",
    costs: { time: 1, clarity: 2, offering: "a former alias" },
    requirements: ["site:Whisper-Knot Shrine"],
    effects: ["mask:gain tag UNNAMED for 3 steps", "recognition:-2 global"],
    verbs_supported: ["invoke", "pledge"],
    echo_triggers: ["name_shed"],
  },
  {
    id: "rite.bind-road",
    name: "Bind the Road",
    domain: "road",
    costs: { time: 1, clarity: 1, offering: "chalk line across boots" },
    requirements: ["site:Milestone XIII"],
    effects: ["travel:+1 success on next leg", "hazard:road -1 tier once"],
    verbs_supported: ["invoke", "travel"],
    echo_triggers: ["road_bound"],
  },
  {
    id: "rite.share-breath",
    name: "Share Breath",
    domain: "spirit",
    costs: { time: 1, clarity: 1 },
    requirements: ["relic:Knot of True Breath"],
    effects: ["pledge:+1 with named witness", "faction:+1 Lantern Court"],
    verbs_supported: ["pledge", "invoke"],
    echo_triggers: ["oath_witnessed"],
  },
  {
    id: "rite.seal-memory",
    name: "Seal a Memory",
    domain: "memory",
    costs: { time: 2, clarity: 2, offering: "salt pinch" },
    requirements: ["relic:Memory Vial", "site:Salt-Glass Observatory"],
    effects: ["remember:convert rumor→echo bias for next run"],
    verbs_supported: ["remember", "scribe"],
    echo_triggers: ["memory_sealed"],
  },
  {
    id: "rite.wake-the-well",
    name: "Wake the Well",
    domain: "spirit",
    costs: { time: 1, clarity: 2, offering: "true statement" },
    requirements: ["site:Whispering Well"],
    effects: ["study:reveal hidden hazard until dusk"],
    verbs_supported: ["invoke", "study"],
    echo_triggers: ["well_awakened", "truth_offered"],
  },
  {
    id: "rite.mask-baptism",
    name: "Mask Baptism",
    domain: "identity",
    costs: { time: 2, clarity: 1, offering: "new mask name" },
    requirements: ["site:Maskwright Hall", "relic:Blank Reed Mask"],
    effects: ["mask:add tag BAPTIZED", "recognition:+2 with Maskwrights"],
    verbs_supported: ["mask", "scribe"],
    echo_triggers: ["mask_forged"],
  },
  {
    id: "rite.thorn-vow",
    name: "Thorn Vow",
    domain: "oath",
    costs: { time: 1, clarity: 2, offering: "blood from a thorn prick" },
    requirements: ["site:Briar Gate"],
    effects: ["pledge:+2 strength vs Roadkeepers", "mark:THORN-SCARRED"],
    verbs_supported: ["pledge", "invoke"],
    echo_triggers: ["oath_sworn", "scar_marked"],
  },
  {
    id: "rite.stone-witness",
    name: "Stone Witness",
    domain: "memory",
    costs: { time: 1, clarity: 1, offering: "engraving on a stone" },
    requirements: ["site:Glassbone Spire"],
    effects: ["remember:rumor → permanent echo", "claim:+1 durability if witnessed"],
    verbs_supported: ["scribe", "remember"],
    echo_triggers: ["memory_engraved"],
  },
  {
    id: "rite.name-crossing",
    name: "Name Crossing",
    domain: "identity",
    costs: { time: 1, clarity: 2, offering: "spoken alias discarded" },
    requirements: ["site:Thorn Cantor’s Hut"],
    effects: ["mask:add tag CROSS-NAMED", "recognition:+1 with Ivythorn faction"],
    verbs_supported: ["pledge", "invoke"],
    echo_triggers: ["name_crossed"],
  },
  {
    id: "rite.salt-absolution",
    name: "Salt Absolution",
    domain: "spirit",
    costs: { time: 2, clarity: 1, offering: "salt poured on ground" },
    requirements: ["site:Brine Mill"],
    effects: ["study:remove one corruption mark", "faction:Salt Covenant +1"],
    verbs_supported: ["invoke", "study"],
    echo_triggers: ["absolution_granted"],
  },
  {
    id: "rite.ember-vigil",
    name: "Ember Vigil",
    domain: "fire",
    costs: { time: 1, clarity: 1, offering: "coal kept alight overnight" },
    requirements: ["site:Smoking Forge"],
    effects: ["invoke:gain temporary MARK:EMBER-BEARER", "clarity:+1 next dawn"],
    verbs_supported: ["invoke", "remember"],
    echo_triggers: ["ember_kept"],
  },
  {
    id: "rite.fen-offering",
    name: "Fen Offering",
    domain: "shadow",
    costs: { time: 1, clarity: 2, offering: "reed bundle lit at marsh" },
    requirements: ["site:Peatfire Kiln"],
    effects: ["invoke:gain favor of Mirebound", "pressure:scarcity -2 local"],
    verbs_supported: ["invoke", "pledge"],
    echo_triggers: ["fen_appeased"],
  },
  {
    id: "rite.stone-witnessing",
    name: "Stone Witnessing",
    domain: "memory",
    costs: { time: 1, clarity: 2, offering: "engrave oath on basalt" },
    requirements: ["site:Smoking Forge"],
    effects: ["scribe:convert pledge into permanent echo", "faction:Maskwrights +1"],
    verbs_supported: ["scribe", "pledge"],
    echo_triggers: ["oath_engraved"],
  },
  {
    id: "rite.oath-of-thirteen",
    name: "Oath of Thirteen",
    domain: "road",
    costs: { time: 1, clarity: 2, offering: "thirteen grains of salt" },
    requirements: ["site:White Road Gate", "site:Milestone XIII"],
    effects: ["pledge:+2 on next road bargain", "travel:ignore tier-2 road hazard once"],
    verbs_supported: ["pledge", "invoke"],
    echo_triggers: ["thirteen_sworn"],
  },
  {
    id: "rite.brine-lustration",
    name: "Brine Lustration",
    domain: "spirit",
    costs: { time: 1, clarity: 1, offering: "hands washed in brine" },
    requirements: ["site:Brine Mill", "relic:Brine Bell"],
    effects: ["study:remove one FEVERED or HAUNTED once", "faction:Salt Covenant +1"],
    verbs_supported: ["invoke", "study"],
    echo_triggers: ["lustration_complete"],
  },
  {
    id: "rite.unseaming",
    name: "Mask Unseaming",
    domain: "identity",
    costs: { time: 2, clarity: 2, offering: "old mask cut along seam" },
    requirements: ["site:Maskwright Hall", "relic:Basalt Chisel"],
    effects: ["mask:retire one mask for recognition refund", "remember:add mask name to future name bank"],
    verbs_supported: ["mask", "scribe"],
    echo_triggers: ["mask_retired"],
  },
  {
    id: "rite.reed-lullaby",
    name: "Reed Lullaby",
    domain: "shadow",
    costs: { time: 1, clarity: 1, offering: "soft song to the fen" },
    requirements: ["site:Bog Lantern Post", "relic:Mire Reed-Flute"],
    effects: ["invoke:reduce rumor_heat by 2 locally", "hazard:fen -1 tier for 1 step"],
    verbs_supported: ["invoke", "remember"],
    echo_triggers: ["fen_quieted"],
  },
  {
    id: "rite.star-reckoning",
    name: "Star Reckoning",
    domain: "memory",
    costs: { time: 2, clarity: 2, offering: "night kept without sleep" },
    requirements: ["site:Salt-Glass Observatory", "relic:Glassbone Splinter"],
    effects: ["remember:promote one clue into echo bias", "study:reveal distant route"],
    verbs_supported: ["remember", "study"],
    echo_triggers: ["stars_read"],
  },
  {
    id: "rite.ivy-binding",
    name: "Ivy Binding",
    domain: "oath",
    costs: { time: 1, clarity: 2, offering: "ivy cord tied to wrist" },
    requirements: ["site:Hush Grove"],
    effects: ["pledge:+1 vs Maskwrights", "mark:IVY-BOUND"],
    verbs_supported: ["pledge", "invoke"],
    echo_triggers: ["ivy_bound"],
  },
  {
    id: "rite.gallows-recital",
    name: "Gallows Recital",
    domain: "memory",
    costs: { time: 1, clarity: 1, offering: "recited name of dead" },
    requirements: ["site:Fen Gallows"],
    effects: ["remember:lost mask name added to next run", "clarity:-1 now"],
    verbs_supported: ["remember", "scribe"],
    echo_triggers: ["dead_named"],
  },
  {
    id: "rite.choir-resonance",
    name: "Choir Resonance",
    domain: "music",
    costs: { time: 1, clarity: 1, offering: "stone struck with reed mallet" },
    requirements: ["site:Basalt Choir"],
    effects: ["invoke:next song ritual doubled", "pressure:rumor_heat +1"],
    verbs_supported: ["invoke", "remember"],
    echo_triggers: ["song_echoed"],
  },
  {
    id: "rite.star-oath",
    name: "Star Oath",
    domain: "memory",
    costs: { time: 2, clarity: 2, offering: "constellation drawn in sand" },
    requirements: ["site:Glassbone Annex"],
    effects: ["pledge:+2 vs Salt Covenant", "rumor:new constellation bias"],
    verbs_supported: ["pledge", "scribe"],
    echo_triggers: ["star_oath"],
  },
  {
    id: "rite.monastic-vigil",
    name: "Monastic Vigil",
    domain: "identity",
    costs: { time: 2, clarity: 1, offering: "silent night fast" },
    requirements: ["site:Cliff Monastery"],
    effects: ["mark:VIGIL-KEEPER", "recognition:+1 with Maskwrights"],
    verbs_supported: ["invoke", "remember"],
    echo_triggers: ["vigil_kept"],
  },
];