/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/
import { SiteDef } from './types';

// This file was converted from JSON to a TS module to resolve browser import issues.
export const SITE_DEFS: SiteDef[] = [
    { id: 'ruin_ancient', name: 'Ancient Ruin', tags: ['ruin', 'ancient'] },
    { id: 'shrine_forgotten', name: 'Forgotten Shrine', tags: ['shrine', 'sacred'] },
    { id: 'camp_abandoned', name: 'Abandoned Camp', tags: ['camp'] },
    { id: 'outpost_watch', name: 'Watchtower Outpost', tags: ['outpost', 'military'] },
    { id: 'grove_sacred', name: 'Sacred Grove', tags: ['grove', 'sacred'] },
    { id: 'oasis_hidden', name: 'Hidden Oasis', tags: ['oasis', 'water'] },
    { id: 'village_fishing', name: 'Fishing Village', tags: ['village', 'settlement'] },
    {
      id: "site.shrine.whisper-knot",
      name: "Whisper-Knot Shrine",
      biome: "ash-fen",
      factions: ["Lantern Court", "Maskwrights"],
      risk: { tier: 2 },
      rarity: "uncommon",
      tags: ["shrine", "oath", "spirit"],
      verbs_supported: ["invoke", "pledge", "remember", "study"],
      hooks: [
        "A braided reed-knot hums when you breathe a name.",
        "A watcher mask hangs, blindfolded with salt-cloth.",
      ],
      state: { type: "dormant", data: {} },
      echo_triggers: ["oath_sworn", "oath_broken", "mask_forged"],
    },
    {
      id: "site.ruin.salt-glass-observatory",
      name: "Salt-Glass Observatory",
      biome: "salt-steppe",
      factions: ["Salt Covenant"],
      risk: { tier: 3 },
      rarity: "rare",
      tags: ["ruin", "star", "memory"],
      verbs_supported: ["search", "study", "scribe", "remember", "claim"],
      hooks: ["Lenses crusted with salt remember last skies."],
      state: { type: "sealed", data: { wards: 1 } },
      echo_triggers: ["site_sanctified", "memory_recovered"],
    },
    {
      id: "site.market.caravan-of-thorns",
      name: "Caravan of Thorns",
      biome: "ivythorn",
      factions: ["Roadkeepers"],
      risk: { tier: 2 },
      rarity: "common",
      tags: ["market", "barter", "rumor"],
      verbs_supported: ["barter", "ask_about", "travel"],
      hooks: ["Traders swap rumors for small oaths."],
      state: { type: "moving", data: { route: "east-west" } },
      echo_triggers: ["rumor_seeded", "deal_struck"],
    },
    {
      id: "site.enclave.maskwright-hall",
      name: "Maskwright Hall",
      biome: "basalt-ridge",
      factions: ["Maskwrights"],
      risk: { tier: 2 },
      rarity: "uncommon",
      tags: ["craft", "mask", "name"],
      verbs_supported: ["mask", "scribe", "barter", "ask_about"],
      hooks: ["Empty visages await their first names."],
      state: { type: "occupied", data: { artisans: 3 } },
      echo_triggers: ["mask_forged", "mask_retired"],
    },
    {
      id: "site.well.whispering",
      name: "Whispering Well",
      biome: "drowned-vale",
      factions: ["Mirebound"],
      risk: { tier: 3 },
      rarity: "uncommon",
      tags: ["water", "spirit", "toll"],
      verbs_supported: ["invoke", "remember", "study"],
      hooks: ["Voices surface when you drop a true thing."],
      state: { type: "sated", data: { last_truth: null } },
      echo_triggers: ["truth_offered", "spirit_bound"],
    },
    {
      id: "site.road.milestone.xiii",
      name: "Milestone XIII",
      biome: "amber-dunes",
      factions: ["Roadkeepers"],
      risk: { tier: 1 },
      rarity: "common",
      tags: ["road", "travel", "rumor"],
      verbs_supported: ["travel", "ask_about", "remember"],
      hooks: ["The number is freshly repainted, slightly wrong."],
      state: { type: "intact", data: {} },
      echo_triggers: ["journey_marked"],
    },
    {
      id: "site.archive.sinking",
      name: "Sinking Archive",
      biome: "ash-fen",
      factions: ["Mirebound"],
      risk: { tier: 3 },
      rarity: "rare",
      tags: ["archive", "ruin", "memory"],
      verbs_supported: ["search", "study", "remember", "claim"],
      hooks: ["Shelves tilt beneath dark water, books swollen with secrets."],
      state: { type: "flooded", data: { depth: 2 } },
      echo_triggers: ["memory_recovered", "archive_ruined"],
    },
    {
      id: "site.spire.glassbone",
      name: "Glassbone Spire",
      biome: "amber-dunes",
      factions: ["Salt Covenant"],
      risk: { tier: 4 },
      rarity: "mythic",
      tags: ["spire", "relic", "hazard"],
      verbs_supported: ["study", "invoke", "claim"],
      hooks: ["A tower of fused sand, ringing like bone when struck."],
      state: { type: "unstable", data: { cracks: 5 } },
      echo_triggers: ["site_claimed", "collapse_recorded"],
    },
    {
      id: "site.gate.briar",
      name: "Briar Gate",
      biome: "ivythorn",
      factions: ["Roadkeepers"],
      risk: { tier: 2 },
      rarity: "uncommon",
      tags: ["gate", "road", "barter"],
      verbs_supported: ["travel", "barter", "ask_about"],
      hooks: ["Thorn-wrapped posts lean, their tollkeeper long vanished."],
      state: { type: "abandoned", data: {} },
      echo_triggers: ["gate_passed", "toll_unpaid"],
    },
    {
      id: "site.kiln.peatfire",
      name: "Peatfire Kiln",
      biome: "ash-fen",
      factions: ["Mirebound"],
      risk: { tier: 2 },
      rarity: "uncommon",
      tags: ["kiln", "craft", "fire"],
      verbs_supported: ["study", "barter", "remember"],
      hooks: ["The ground smolders; clay jars blacken in the smoke."],
      state: { type: "lit", data: { fires: 3 } },
      echo_triggers: ["artifact_fired", "kiln_collapsed"],
    },
    {
      id: "site.cistern.wanderer",
      name: "Wanderer’s Cistern",
      biome: "amber-dunes",
      factions: ["Roadkeepers"],
      risk: { tier: 2 },
      rarity: "common",
      tags: ["cistern", "water", "travel"],
      verbs_supported: ["travel", "invoke", "remember"],
      hooks: ["Carved steps lead into a half-buried pool, etched with tally marks."],
      state: { type: "half_full", data: {} },
      echo_triggers: ["journey_marked", "cistern_sanctified"],
    },
    {
      id: "site.hut.cantor",
      name: "Thorn Cantor’s Hut",
      biome: "ivythorn",
      factions: ["Maskwrights"],
      risk: { tier: 1 },
      rarity: "common",
      tags: ["hut", "song", "oath"],
      verbs_supported: ["ask_about", "invoke", "pledge"],
      hooks: ["A lone hut draped in ivy; chants drift through its doorway."],
      state: { type: "occupied", data: { cantor: true } },
      echo_triggers: ["song_learned", "oath_chanted"],
    },
    {
      id: "site.mill.brine",
      name: "Brine Mill",
      biome: "salt-steppe",
      factions: ["Salt Covenant"],
      risk: { tier: 3 },
      rarity: "uncommon",
      tags: ["mill", "salt", "craft"],
      verbs_supported: ["barter", "study", "claim"],
      hooks: ["A windmill crusted white with salt dust groans in the wind."],
      state: { type: "operational", data: { stockpiles: 2 } },
      echo_triggers: ["salt_milled", "mill_ruined"],
    },
    {
      id: "site.forge.smoking",
      name: "Smoking Forge",
      biome: "basalt-ridge",
      factions: ["Maskwrights"],
      risk: { tier: 3 },
      rarity: "rare",
      tags: ["forge", "craft", "relic"],
      verbs_supported: ["study", "barter", "mask"],
      hooks: ["Hammers strike within smoke-thick halls of volcanic stone."],
      state: { type: "active", data: { smiths: 2 } },
      echo_triggers: ["relic_forged", "forge_ruined"],
    },
    {
      id: "site.post.bog-lantern",
      name: "Bog Lantern Post",
      biome: "ash-fen",
      factions: ["Lantern Court", "Mirebound"],
      risk: { tier: 2 },
      rarity: "common",
      tags: ["watch", "light", "rumor"],
      verbs_supported: ["ask_about", "remember", "study"],
      hooks: ["Green fire burns smokeless atop a leaning pole of peatwood."],
      state: { type: "manned", data: { wardens: 1 } },
      echo_triggers: ["warning_posted", "lantern_fallen"],
    },
    {
      id: "site.court.reed",
      name: "Reed Court",
      biome: "ash-fen",
      factions: ["Mirebound"],
      risk: { tier: 2 },
      rarity: "uncommon",
      tags: ["court", "oath", "claim"],
      verbs_supported: ["pledge", "claim", "ask_about", "scribe"],
      hooks: ["Judges in reed masks settle disputes by traded names."],
      state: { type: "in_session", data: { docket: 3 } },
      echo_triggers: ["claim_adjudicated", "oath_recorded"],
    },
    {
      id: "site.gate.white-road",
      name: "White Road Gate",
      biome: "salt-steppe",
      factions: ["Roadkeepers", "Salt Covenant"],
      risk: { tier: 2 },
      rarity: "common",
      tags: ["gate", "road", "toll"],
      verbs_supported: ["travel", "barter", "ask_about"],
      hooks: ["A chalk-white arch marks entry to the salt plains."],
      state: { type: "guarded", data: { toll: 1 } },
      echo_triggers: ["gate_passed", "toll_disputed"],
    },
    {
      id: "site.choir.basalt",
      name: "Basalt Choir",
      biome: "basalt-ridge",
      factions: ["Maskwrights"],
      risk: { tier: 3 },
      rarity: "rare",
      tags: ["music", "echo", "craft"],
      verbs_supported: ["study", "invoke", "scribe"],
      hooks: ["Pipes carved in the cliff sing when the wind shifts."],
      state: { type: "resonant", data: { tone: "low" } },
      echo_triggers: ["hymn_learned", "rocksong_awakened"],
    },
    {
      id: "site.dais.sand-choir",
      name: "Sand Choir Dais",
      biome: "amber-dunes",
      factions: ["Roadkeepers"],
      risk: { tier: 2 },
      rarity: "uncommon",
      tags: ["ritual", "journey", "song"],
      verbs_supported: ["invoke", "remember", "pledge"],
      hooks: ["A ring of stone seats half-buried in rippling dunes."],
      state: { type: "quiet", data: {} },
      echo_triggers: ["journey_blessed", "song_offered"],
    },
    {
      id: "site.gallows.fen",
      name: "Fen Gallows",
      biome: "ash-fen",
      factions: ["Mirebound", "Lantern Court"],
      risk: { tier: 3 },
      rarity: "uncommon",
      tags: ["execution", "memory", "spirit"],
      verbs_supported: ["remember", "invoke", "claim"],
      hooks: ["A half-sunk scaffold where moss-ropes sway in the fog."],
      state: { type: "abandoned", data: {} },
      echo_triggers: ["gallows_seen", "spirit_appeased"],
    },
    {
      id: "site.spire.glassbone-annex",
      name: "Glassbone Annex",
      biome: "amber-dunes",
      factions: ["Salt Covenant"],
      risk: { tier: 2 },
      rarity: "uncommon",
      tags: ["ruin", "star", "relic"],
      verbs_supported: ["study", "search", "scribe"],
      hooks: ["A smaller tower cracked from the main spire, littered with shards."],
      state: { type: "ruined", data: { stability: 1 } },
      echo_triggers: ["shard_found", "annex_collapsed"],
    },
    {
      id: "site.grove.hush",
      name: "Hush Grove",
      biome: "ivythorn",
      factions: ["Maskwrights"],
      risk: { tier: 2 },
      rarity: "common",
      tags: ["grove", "silence", "mask"],
      verbs_supported: ["study", "remember", "invoke"],
      hooks: ["Ivy-choked trunks bow together, swallowing sound entirely."],
      state: { type: "silent", data: {} },
      echo_triggers: ["silence_kept", "grove_awakened"],
    },
    {
      id: "site.monastery.cliff",
      name: "Cliff Monastery",
      biome: "basalt-ridge",
      factions: ["Maskwrights", "Roadkeepers"],
      risk: { tier: 3 },
      rarity: "rare",
      tags: ["monastery", "oath", "claim"],
      verbs_supported: ["pledge", "scribe", "ask_about"],
      hooks: ["A ladder-carved cliff face hides shrines where monks tally vows."],
      state: { type: "inhabited", data: { monks: 4 } },
      echo_triggers: ["oath_recorded", "monastery_fallen"],
    },
    {
      id: "site.jetty.bellboat",
      name: "Bellboat Jetty",
      biome: "drowned-vale",
      factions: ["Mirebound"],
      risk: { tier: 2 },
      rarity: "common",
      tags: ["dock", "ferry", "rumor"],
      verbs_supported: ["travel", "barter", "ask_about"],
      hooks: ["Waterlogged planks creak; a bell tolls when boats depart."],
      state: { type: "operational", data: { boats: 1 } },
      echo_triggers: ["journey_departed", "ferry_sunk"],
    },
];